### ISSUE TITLE
如何改成AppCompatActivity

### ISSUE THREAD

**Issue by geeklx** [stray-coding/PluginApk#1]
如何改成AppCompatActivity 谢谢回复

**Comment by stray-coding** [comment]
如果你想使用插件apk中的AppCompatActivity ，可以直接将plugin module中的ProxyActivity继承AppCompatActivity即可。

**Comment by geeklx** [comment]
不行的，我试过了，崩溃，这个是原因，不知道怎么写，博主看看怎么改造一下，谢谢~
https://weichao.io/2020/04/09/%E6%8F%92%E4%BB%B6%E5%8C%96/

**Comment by stray-coding** [comment]
插件中使用资源不能用R.id.name，需要使用我提供的PluginResUtils类

**Comment by geeklx** [comment]
只改变class ProxyActivity : AppCompatActivity() {
和
public abstract class PluginActivity extends AppCompatActivity implements PluginInterface {

崩溃

其他代码不变

**Comment by stray-coding** [comment]
我有空的时候去复现一下吧！解决了，到时候再回复你！

**Comment by geeklx** [comment]
好的 能加个好友吗大佬 729490254

**Comment by geeklx** [comment]
崩溃日志：

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
        at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:211)
        at android.view.ContextThemeWrapper.getTheme(ContextThemeWrapper.java:175)
        at android.content.Context.obtainStyledAttributes(Context.java:753)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:839)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
        at androidx.appcompat.app.AppCompatDelegateImpl.findViewById(AppCompatDelegateImpl.java:630)
        at androidx.appcompat.app.AppCompatActivity.findViewById(AppCompatActivity.java:223)
        at com.coding.other.Main1Activity.onCreate(Main1Activity.kt:20)
        at com.coding.plugin.ProxyActivity.onCreate(ProxyActivity.kt:40)
        at android.app.Activity.performCreate(Activity.java:8093)
        at android.app.Activity.performCreate(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3465)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2099) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:7892) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
2021-08-16 11:03:46.975 15306-15306/? E/AppBackListener: onTopAppChanged newApp=com.miui.home,oldApp=com.coding.pluginapk,mPersistentApp=null,innerApp=false

**Comment by stray-coding** [comment]
最近稍微看了一下这个问题，目前AppCompatActivity坑有点多，解决了一个又会冒出其他的问题，建议你看看能不能用其他Activity代替吧

**Comment by geeklx** [comment]
很多三方库都是AppCompatActivity，不支持就废了，我也在想办法，感谢大佬，一起想想

**Comment by stray-coding** [comment]
看最新的提交！

**Comment by geeklx** [comment]
我试了一下不行，大佬，只使用本身的资源和方法是没问题的，但是接入第三方资源方法后就报错，比如：
 new XPopup.Builder(getBaseContext())
//                        .maxWidth(600)
                        .maxHeight(800)
                        .isDarkTheme(true)
                        .isDestroyOnDismiss(true) //对于只使用一次的弹窗，推荐设置这个
                        .asCenterList("请选择一项", new String[]{"条目1", "条目2", "条目3", "条目4", "条目1", "条目2", "条目3", "条目4",
                                        "条目1", "条目2", "条目3", "条目4", "条目1", "条目2", "条目3", "条目4",
                                        "条目1", "条目2", "条目3", "条目4", "条目1", "条目2", "条目3", "条目4",
                                        "条目1", "条目2", "条目3", "条目4", "条目1", "条目2", "条目3", "条目4",
                                        "条目1", "条目2", "条目3", "条目4", "条目1", "条目2", "条目3", "条目4",},
                                new OnSelectListener() {
                                    @Override
                                    public void onSelect(int position, String text) {
//                                        toast("click " + text);
                                    }
                                })
//                        .bindLayout(R.layout.my_custom_attach_popup) //自定义布局
                        .show();


报错信息：
lang.NullPointerException: Attempt to write to field 'int android.widget.FrameLayout$LayoutParams.gravity' on a null object reference
        at com.lxj.xpopup.core.CenterPopupView.addInnerContent(CenterPopupView.java:34)
        at com.lxj.xpopup.impl.CenterListPopupView.<init>(CenterListPopupView.java:43)
        at com.lxj.xpopup.XPopup$Builder.asCenterList(XPopup.java:697)
        at com.lxj.xpopup.XPopup$Builder.asCenterList(XPopup.java:706)
        at com.lxj.xpopup.XPopup$Builder.asCenterList(XPopup.java:710)
        at com.coding.other.Main2Activity$1.onClick(Main2Activity.java:28)
        at android.view.View.performClick(View.java:7567)
        at android.view.View.performClickInternal(View.java:7544)
        at android.view.View.access$3600(View.java:836)


修改添加第三方代码如下：
https://github.com/geeklx/pluginapk

**Comment by stray-coding** [comment]
我写了版hook版的插件apk，兼容activity和AppCompatActivity    代码放到https://github.com/stray-coding/HookActivity/tree/master   这里了，相对之前来说坑比较少，兼容性更广，你可以看一下

**Comment by geeklx** [comment]
感谢大佬，还是不行，报错信息如下：

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.coding.demo/com.coding.plugin.PlaceholderActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3492)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3652)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2099)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.coding.plugin.PluginActivity.onCreate(PluginActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:8093)
        at android.app.Activity.performCreate(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)

**Comment by geeklx** [comment]
添加第三方库后的代码地址：https://github.com/geeklx/HookActivity
