### ISSUE TITLE
我在插件other的activity集成了一个sdk

### ISSUE THREAD

**Issue by huangzhewei** [stray-coding/PluginApk#2]
我在插件other的activity集成了一个sdk这个sdk本身会用到mmkv这个库 所以我在other加了依赖 , 这个sdk会application初始化,但我看了插件好像不支持application初始化的 所以我放在了activity里初始化并引用了PluginActivity的上下文 , 结果出现崩溃情况  我猜是sdk自身要引用sdk的时候基于插件化的环境无法加载so   请问要怎么解决呢   以下代码报错提示:
/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.coding.pluginapk, PID: 9006
    java.lang.UnsatisfiedLinkError: dalvik.system.DexClassLoader[DexPathList[[zip file "/data/user/0/com.coding.pluginapk/app_patch/other-debug.apk"],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64]]] couldn't find "libmmkv.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1073)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:209)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:191)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:134)
        at com.fvbox.lib.FCore.init(:18)
        at com.fvbox.lib.FCore.init(:1)
        at com.coding.other.Main1Activity.onCreate(Main1Activity.kt:25)
        at com.coding.plugin.ProxyActivity.onCreate(ProxyActivity.kt:40)
        at android.app.Activity.performCreate(Activity.java:8397)
        at android.app.Activity.performCreate(Activity.java:8370)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3842)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.app.ActivityThread.main(ActivityThread.java:8364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by huangzhewei** [comment]
请加下我QQ 972410715方便联系
